const Data = [
  {
    id: 1,
    category: "experience",
    icon: "icon-briefcase",
    year: "Jan.2021 - present",
    title: "Technical Support Specialist (part-time)",
    subtitle: "Vidéotron, Montréal",
    desc: "My four-year journey here was full of learning: fundamentals of networking, ticketing, troubleshooting, and escalation. I discovered I could solve problems I didn’t even know I could... and survive the IT battlefield 🛡️",
  },
  {
    id: 2,
    category: "experience",
    icon: "icon-briefcase",
    year: "May.2025 - Aug.2025",
    title: "Software Engineer Intern",
    subtitle: "Société Générale, Montréal",
    desc: "This internship was magical ✨ It pushed me beyond my knowledge and limits, and I discovered that I can actually thrive in big teams at major companies. I picked up new tools, true AGILE skills, YAML scripts, Docker magic, project delivery to production, and cloud migration of legacy systems all while untangling legacy financial system puzzles 🧩",
  },
  {
    id: 3,
    category: "experience",
    icon: "icon-briefcase",
    year: "Jan.2020 - Nov.2020",
    title: "Junior Software Developer",
    subtitle: "Premicesoft, Dollars-des-Ormeaux",
    desc: "This is my first official software dev quest! That’s where I truly entered the dev world. I started by debugging legacy apps, updating, and documenting (aka. fighting ancient code monsters). Then I leveled up, building the foundation for a new project: a mobile tracker system for snow removal companies ❄️",
  },
  {
    id: 4,
    category: "experience",
    icon: "icon-briefcase",
    year: "June.2019 - July.2019",
    title: "Front-End Developer Intern",
    subtitle: "Sponteous, HEC Montréal",
    desc: "Technically my second internship. Honestly, not too much, I coded a map component for a travel agency so that users could see their chosen destinations connected on a single integrated map 🗺️📍",
  },
  {
    id: 5,
    category: "experience",
    icon: "icon-briefcase",
    year: "Oct.2018 - Jan.2020",
    title: "Customer Service (part-time student job)",
    subtitle: "Best Buy, Montréal",
    desc: "This was my very first real dive into the wild world of work: exploring markets, revenue numbers, and customer chats... Basically leveling up out of my comfort zone ⬆️",
  },
  {
    id: 6,
    category: "education",
    icon: "icon-graduation",
    year: "Sept.2022 - May.2026",
    title: "BEng. Software Engineering",
    subtitle: "Concordia University",
    desc: "Four years of theory overload, coding mostly in Java and Python, with cameos by Clojure, Lisp, and Erlang. And yes, the big boss? Software design. ⚡",
  },
  {
    id: 7,
    category: "education",
    icon: "icon-graduation",
    year: "Jan.2018 - Mar.2020",
    title: "Technical College Degree (DEC)",
    subtitle: "Teccart Institute",
    desc: "Well, here I basically lived in code 😌. We covered : Python, C++, C#, Java, Kotlin, and my old buddy PHP. We even went full web-warrior mode with ASP, JS, React-Redux, and the whole toolbox. 🛠️",
  },
  {
    id: 8,
    category: "education",
    icon: "icon-graduation",
    year: "Sept.2015 - Dec.2017",
    title: "Associate Degree in engineering sciences",
    subtitle: "Hassan II University - Mohammedia",
    desc: "Wild adventure through the realms of science: from taming data structures in C and wrestling databases queries, to decoding the mysteries of quantum physics and electromagnetics. (I even survived the chemical jungles of chemistry)",
  },
  {
    id: 9,
    category: "certification",
    icon: "icon-badge",
    year: "2025",
    title: "Cybersecurity and WIL Program",
    subtitle: "ICTC-CTWIL",
    desc: "Cybersecurity . Information Security . Generative AI",
  },
  {
    id: 10,
    category: "certification",
    icon: "icon-badge",
    year: "2024",
    title: "AZ-900 : Azure Fundamentals",
    subtitle: "Microsoft",
    desc: "Cloud Computing . Cloud Security . Cloud Migration",
  },
  {
    id: 11,
    category: "certification",
    icon: "icon-badge",
    year: "2020",
    title: "Graphic Design Masterclass",
    subtitle: "Udemy",
    desc: "Mastered : Adobe Photoshop . Adobe Illustrator . Adobe InDesign",
  },
];

export default Data;
